### ISSUE TITLE
Language translations

### ISSUE THREAD

**Issue by pdifeo** [laravel/jetstream#59]
Hi,

I'm newbie on jetstream. I see that all blades templates have no key references for translations. 

is it planned in the future ?

Best regards
Pasquale

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/laravel/jetstream/pull/81

**Comment by pdifeo** [comment]
Hi, 
thanks for the fast solution. But this is only on auth forms. The issue still remain on profile, teams views and app.blade.php .

In a nutshell I can modify but what happens if you release a new version ?

Thanks in advance.
Pasquale

**Comment by jbrooksuk** [comment]
Feel free to make a PR :)
